### ISSUE TITLE
Twisted avatar feet when attempting to calibrate FBT

### ISSUE THREAD

**Issue by RazzleDazzleDaeris** [nicoco007/BeatSaberCustomAvatars#104]
**Before doing anything else, please attach your latest log to this issue. It should be located at `Logs\_latest.log` in your Beat Saber installation's folder.**

_**Log attached here:**_ [_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/6457710/_latest.log)

**Desktop (please complete the following information):**
- Operating system: [e.g. Windows 10, Ubuntu 18.04]
_I am using Windows 10_

- Headset and controllers: [e.g. Oculus Rift, HTC Vive, Valve Index]
_I am using Valve Index with 2 Index knuckles controllers, and 2 old HTC Vive 1.0 lighthouses, using 3 HTC Vive puck trackers_

**Describe the bug**
_When I press the Calibrate button to calibrate FBT with my avatars, all of the avatars end up with twisted feet, making it impossible for me to actually line up and calibrate my trackers to the avatar. When I attempt to turn on Bypass Calibration, the same thing occurs, however the feet are twisted a bit differently._

_I saw another bug report submit on this issue in March 2021 (by fuyushi), however I did not see a fix indicated, nor have I been able to locate how to fix this issue yet._

_This happens with every custom avatar I have installed._

**Steps to reproduce**
1. _Go to Custom Avatars menu_
2. _Click on an Avatar and then try to FBT Calibrate_
3. _When you click Calibrate the feet will twist in a way that makes it impossible to calibrate FBT_
4. _When you try to Bypass Calibration, the feet will twist as well, but a little differently_

**Expected behavior**
A clear and concise description of what you expected to happen: _I expect the avatar to enter into a T-pose, or some kind of basic pose so I can then FBT calibrate my trackers to the avatar. The twisted feet make it impossible to calibrate._

**Screenshots**

_When you click Calibrate:_
![Screen Shot 05-11-21 at 04 46 AM](https://user-images.githubusercontent.com/82847163/117786810-e4f02c00-b213-11eb-9b7f-d412e0fb42ea.PNG)

_When you try to Bypass Calibration:_
![Screen Shot 05-11-21 at 04 46 AM 001](https://user-images.githubusercontent.com/82847163/117786931-ff2a0a00-b213-11eb-8ed2-5d2214100e20.PNG)

**Comment by nicoco007** [comment]
Could you try updating to [version 5.2.2](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.2.2)? This issue should have been fixed in that release.

**Comment by RazzleDazzleDaeris** [comment]
> Could you try updating to [version 5.2.2](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.2.2)? This issue should have been fixed in that release.

Oh you know what, I am still on 5.2.1. I'm so sorry. However, it seems when I try to update using Mod Assistant, it doesn't update to 5.2.2.

Should I download the release here and install manually? I've never seen Mod Assistant not install the latest version. I also uninstall and reinstall using Mod Assistant and it still doesn't go to 5.2.2.

![Screen Shot 05-11-21 at 10 15 PM](https://user-images.githubusercontent.com/82847163/117908610-b7a08e00-b2a6-11eb-82d1-3be4cb1f140d.PNG)

**Comment by nicoco007** [comment]
No need to be sorry! Releasing on GitHub and on Mod Assistant are two different processes &ndash; I have to wait for the mod to go through approval before it appears on Mod Assistant, so it'll always be available here on GitHub a few days earlier. You can definitely install it manually from [the release page](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.2.2) (there are some instructions [in the readme](https://github.com/nicoco007/BeatSaberCustomAvatars#installing-manually); if you have BeatSaberMarkupLanguage and DynamicOpenVR already installed through Mod Assistant you can ignore the first sentence) or you can wait for it to show up on Mod Assistant (I can't guarantee when that'll happen though).

**Comment by nicoco007** [comment]
Since I haven't heard from you in a while, I'm going to assume this is no longer an issue. If you're still having trouble, feel free to open a new issue.
