### ISSUE TITLE
Cant see listed avatars, How to fix?

### ISSUE THREAD

**Issue by Slawsha** [nicoco007/BeatSaberCustomAvatars#58]
Latest Log:
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5082978/_latest.log)

I tried to load up the game and select a custom avatar, and in the avatars menu, it gives me every other option and in the list of custom avatars. Except it shows the player statistics menu in place of the list of available avatars. What is a fix for this?

Here is a screenshot so you know what I mean:
![20200817010202_1](https://user-images.githubusercontent.com/57952497/90374070-c0ba4280-e027-11ea-9dfb-6508d491ef46.jpg)

**Comment by nicoco007** [comment]
Did you extract the `CustomAvatars\Shaders\customavatars.assetbundle` file when installing the mod? It looks like the file being loaded is from an older version.

**Comment by haozi23333** [comment]
game version: 1.11.0
avatars:  5.0.0 RC1 RELEASE
openvr: 0.3.0 RELEASE
openvr-saber  0.3.0 RELEASE

cant display

**Comment by kissmonstar** [comment]
I'm having the exact same issue, and I installed everything fresh as I did a clean wipe of beat saber after the update

**Comment by Interpause** [comment]
will note I am having the same issue as well, also did a fresh reinstall

**Comment by paradox201** [comment]
hey - we are also getting the same issue exactly as pictured above - mod menu all ok - but just get the stats page  - fresh install and have checked CustomAvatars\Shaders\customavatars.assetbundle came from the latest version

**Comment by trudruchocolatemilk** [comment]
same issue here, I also did a clean install, same thing
![sefg](https://user-images.githubusercontent.com/43690740/90539274-9ebae000-e14d-11ea-9967-0f3dcb333fe2.png)

**Comment by nicoco007** [comment]
Could you try [this version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5093254/BeatSaberCustomAvatars-b6e3879-RELEASE.zip) and let me know if it works? If not, could you please attach your latest log? It's the file called `_latest` in the `Logs` folder of your Beat Saber installation.

**Comment by Slawsha** [comment]
This issue actually resolved itself for me yesterday. I just clean installed the game after mods became available again and dragged the folders directly into their respected locations. I used Avatars 5.0.0 and OpenVR 0.2.1 and they worked flawlessly for me. Thanks for your help.

**Comment by rchian3** [comment]
I am having the same issue. I tried the version in the comment above and it didnt work for me.
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5093449/_latest.log)

**Comment by Zerotwo111** [comment]
Having the same issue as well and tried the version you linked with same issues continuing. I linked the lastest log I aint sure what the issue is as I have a fresh install as well like everyone else. 
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5093448/_latest.log)

**Comment by Lynlisss** [comment]
Having the same issue. Did a fresh install of everything and still get the same issue. Latest log is linked. 
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5098892/_latest.log)

**Comment by trudruchocolatemilk** [comment]
same thing
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5099552/_latest.log)

**Comment by trudruchocolatemilk** [comment]
did a clean install and heres the new log
[_latest.log](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5099576/_latest.log)

**Comment by nicoco007** [comment]
My bad, turns out there were a few issues causing this. [This version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5099608/BeatSaberCustomAvatars-e16086f-RELEASE.zip) should hopefully work properly.

**Comment by nalister89** [comment]
That did it!! I can use my avatars again.

**Comment by nicoco007** [comment]
Awesome 😄 I'll just wait a bit to see if I missed anything (again) and then I'll officially release this version.

**Comment by felinearts** [comment]
5.0.0 RC2 fixes everything! <3

**Comment by Lynlisss** [comment]
Yes, yes yes! It works great now! Thank you so much!!!

**Comment by kissmonstar** [comment]
RC2 was a complete success here as well

**Comment by trudruchocolatemilk** [comment]
hell yeah man

**Comment by nicoco007** [comment]
Looks like this is fixed, so I'll close the issue. I'll be releasing RC 2 in a few days since a couple of other issues have cropped up.

**Comment by emerycw7** [comment]
I haven't gotten this to work

**Comment by michaellgmichaellg** [comment]
> My bad, turns out there were a few issues causing this. [This version](https://github.com/nicoco007/BeatSaberCustomAvatars/files/5099608/BeatSaberCustomAvatars-e16086f-RELEASE.zip) should hopefully work properly.

Might be just my setup, blade sorcery also doesnt work, vrchat does work tho, all to state that my body tracking feature isnt supported on any avatar including the template by default

**Comment by singeee** [comment]
Hello! I have a problem with that new custom avatars mod version. Half of my avatars stay on T-Pose while they were working fine with the old version...

**Comment by DrDraxi** [comment]
It doesn't work for me. Neither the new version or the "fix". Still can't see the avatars in the menu and have to restart the game to get out of it. :-/

**Comment by nicoco007** [comment]
@emerycw7 @DrDraxi Looks like there are still some lingering issues since a few other people have also said it's not working [over here](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/60). I'll be posting updates there since the original problem here has been solved.

@michaellgmichaellg You might be having the same problem as what's going on in #40. If that's **not** the case, could you please [open a separate issue](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/new/choose)?

@singeee The problem you're having hasn't been reported yet. Could you please [open a separate issue](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/new/choose)?

**Comment by nicoco007** [comment]
@emerycw7 @DrDraxi Looks like there are still some lingering issues since a few other people have also said it's not working [over here](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/60). I'll be posting updates there since the original problem here has been solved.

@michaellgmichaellg Remember that you have to calibrate or explicitly bypass calibration for full body tracking to work as of beta 8 of Custom Avatars. Also, you might be having the same problem as what's going on in #40. If that's **not** the case, could you please [open a separate issue](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/new/choose)?

@singeee The problem you're having hasn't been reported yet. Could you please [open a separate issue](https://github.com/nicoco007/BeatSaberCustomAvatars/issues/new/choose)?
